version: 2.1

orbs:
  slack: circleci/slack@3.4.2

parameters:
  working_directory:
    type: string
    default: ~/issuewatcher
  python_version:
    type: string
    default: "3.6"

jobs: # A basic unit of work in a run
  test:
    working_directory: << pipeline.parameters.working_directory >>
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python<< parameters.version >>/site-packages
      - restore_cache:
          key: issuewatcher-<< parameters.version >>-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dev libraries
          command: |
            pip install --upgrade pip &&
            pip install pipenv &&
            pipenv install --dev --deploy
      - run:
          name: Format check
          command: pipenv run inv format --check
      - run:
          name: Type check
          command: pipenv run inv typecheck
      - run:
          name: Linters
          command: pipenv run inv lint
      - save_cache:
          key: issuewatcher-<< parameters.version >>-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python<< parameters.version >>/site-packages"
      - run:
          name: Unit tests
          command: |
            pipenv run inv test-unit
      - run:
          name: Build coverage report
          command: pipenv run inv coverage-report
      - store_artifacts:
          path: reports/coverage-report
      - store_test_results:
          path: reports
  build:
    working_directory: << pipeline.parameters.working_directory >>
    docker: # run the steps with Docker
      - image: circleci/python:<< pipeline.parameters.python_version >>
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: issuewatcher-<< pipeline.parameters.python_version >>-{{ checksum "Pipfile.lock" }}
      - run:
          name: Build library
          command: |
            pip install pipenv &&
            pipenv run inv build
      - persist_to_workspace:
          root: << pipeline.parameters.working_directory >>
          paths: .

  deploy_library:
    working_directory: << pipeline.parameters.working_directory >>
    docker: # run the steps with Docker
      - image: circleci/ruby:2.6.5
    steps:
      - attach_workspace:
          at: << pipeline.parameters.working_directory >>
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel
      - run:
          name: Upload to pypi
          command: pipenv run twine upload dist/*
workflows:
  version: 2
  all_pipelines:
    jobs:
      - test:
          name: Python << matrix.version >> tests
          matrix:
            parameters:
              version: ["3.6", "3.7", "3.8", "3.9"]
      - build:
          name: Packages build
          requires:
            - test
      - deploy_library:
          requires:
            - Packages build
          filters:
            branches:
              only: master
